### ISSUE TITLE
[DEX] Dex Geo -> OSS. Dex Scraper -> OSS. End of February.

### ISSUE THREAD

**Issue by lundstrj** [plotly/dash-sample-apps#385]
- [x] https://github.com/plotly/dash-customer-success/issues/185
~~- [ ] https://github.com/plotly/dash-customer-success/issues/186~~
- [x] https://github.com/plotly/dash-customer-success/issues/184
- [x] https://github.com/plotly/dash-customer-success/issues/159
